Repository cea-instn/instart, pull requests merged in 2019-11, with the labels that each got.

#46 Improve solutions responsiveness
  src/frontend/scss/templates/richie/_solutions.scss
Labels: improvement

#47 Improve programs list responsiveness
  src/frontend/scss/objects/_program_glimpses.scss
Labels: improvement

#48 Improve program detail responsiveness
  src/frontend/scss/templates/courses/cms/_program_detail.scss
Labels: improvement

#49 Improve category detail responsiveness
  src/backend/instart/templates/courses/cms/category_detail.html
  src/frontend/scss/templates/courses/cms/_category_detail.scss
Labels: improvement

#52 ⬆️(project) Upgrade richie to 1.14.1
  CHANGELOG.md
  requirements/base.txt
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: dependencies

#55 🔖(major) bump version to 1.0.0
  CHANGELOG.md
Labels: release
