Repository cea-instn/instart, pull requests merged in 2019-10, with the labels that each got.

#28 ⬆️(aws) upgrade terraform syntax to 0.12
  CHANGELOG.md
  src/aws/cloudfront.tf
  src/aws/create_state_bucket/s3.tf
  src/aws/s3.tf
Labels: dependencies

#32 🐳(project) fix sass build in production image
  CHANGELOG.md
  Dockerfile
Labels: bug, critical, needs review

#33 ⬆🔒(dependencies) update vulnerable dependencies to safe versions
  CHANGELOG.md
  src/frontend/yarn.lock
Labels: dependencies

#34 Partners home
  src/backend/instart/settings.py
  src/backend/instart/templates/richie/homepage.html
  src/frontend/scss/objects/_organization_glimpses.scss
  src/frontend/scss/objects/_person_glimpses.scss
Labels: improvement

#36 Responsive
  src/frontend/scss/custom-style/_typography.scss
  src/frontend/scss/layout/_header.scss
  src/frontend/scss/objects/_course_glimpses.scss
  src/frontend/scss/objects/_person_glimpses.scss
  src/frontend/scss/templates/richie/_homepage.scss
Labels: feature, needs review

#37 Responsive news
  src/frontend/scss/objects/_blogpost_glimpses.scss
  src/frontend/scss/templates/courses/cms/_blogpost_detail.scss
Labels: improvement, needs review

#38 :lipstick: Center network icons
  src/frontend/scss/templates/core/social-networks/_social-networks.scss
Labels: improvement, needs review

#39 Make header padding behave like other content
  src/frontend/scss/layout/_header.scss
Labels: improvement, needs review

#40 Responsive search
  src/frontend/scss/objects/_search-filter-value.scss
  src/frontend/scss/templates/search/_search.scss
Labels: improvement, needs review

#41 Responsive experts
  src/frontend/scss/objects/_person_glimpses.scss
  src/frontend/scss/templates/courses/cms/_course_detail.scss
  src/frontend/scss/templates/courses/cms/_person_detail.scss
  src/frontend/scss/templates/richie/_homepage.scss
Labels: improvement

#43 Responsive course detail
  src/frontend/scss/base/_buttons.scss
  src/frontend/scss/templates/courses/cms/_course_detail.scss
Labels: improvement
